# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ARMa2401'
    appType: 'webAppLinux'
    appName: 'pnrdevopswebapp'
    runtimeStack: 
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'